# Generated by Django 4.2.1 on 2023-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_relatedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='relatedmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='relatedmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field1',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field2',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field3',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='field1',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='field2',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='field3',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='field4',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='field5',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
